HLS Sampler: jackson-jaxb-annotations may require jaxb-api in some cases (#517)
* HLS Sampler: jackson-jaxb-annotations may require jaxb-api in some cases

When another JMeter plugin auto-registers Jackson modules, it fails with exception:

> Uncaught Exception java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement in thread Thread[StandardJMeterEngine,5,main]. See log file for details.

* Jaxb required by latest plugin (3.1)