Add configurable aggregate report (#780)
* Add Configurable Aggregate Report plugin along with bug fixes

* Update various.json

* Update various.json

* Update various.json (#777)

looks like libs{} in json broke plugin manager. so i have removed it from my change

2026-03-06 13:38:46,884 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
net.sf.json.JSONException: JSONObject["libs"] is not a JSONObject.
	at net.sf.json.JSONObject.getJSONObject(JSONObject.java:2058) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.Plugin.getLibs(Plugin.java:361) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.DependencyResolver.resolveDeleteLibs(DependencyResolver.java:231) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.DependencyResolver.resolve(DependencyResolver.java:37) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.DependencyResolver.<init>(DependencyResolver.java:28) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.PluginManager.getChangesAsText(PluginManager.java:233) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.PluginManagerDialog$1.notify(PluginManagerDialog.java:64) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.PluginManagerDialog.<init>(PluginManagerDialog.java:114) ~[jmeter-plugins-manager-1.11.jar:?]
	at org.jmeterplugins.repository.PluginManagerMenuItem.actionPerformed(PluginManagerMenuItem.java:101) ~[jmeter-plugins-manager-1.11.jar:?]
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374) ~[?:?]

* Add JTL Excel Smart Report Generator plugin (#778)

* Add JTL Excel Smart Report Generator plugin

* Remove unsupported 'site' property from plugin.json

* Fix downloadUrl to use GitHub release asset

* Remove misplaced plugin descriptor

* Ignore macOS DS_Store files

* Add JTL Excel Smart Report Generator plugin to various.json

* Fix plugin descriptor according to repo schema

* Add Prism - tab-style interface plugin for Apache JMeter (#779)

* Add: Feather Wand - JMeter AI Agent

* Add: Feather Wand - JMeter AI Agent

* Update Feather Wand

* Bump FeatherWand - Claude Code integration

* Update various.json

* Update various.json

* Update various.json

* Add: Prism

* Add Configurable Aggregate Report plugin

* Update various.json

---------

Co-authored-by: Rishav <rishavsawarn@gmail.com>
Co-authored-by: NaveenKumar Namachivayam ⚡ <catch.nkn@gmail.com>